### ISSUE TITLE
Feature request - FHIR Valueset offset parameter support

### ISSUE THREAD

**Issue by scicco** [lhncbc/clin-table-search#8] opened 2021-12-02 11:01 UTC
Hello,

according to this [page](https://clinicaltables.nlm.nih.gov/valueSetExpand.html) the only supported FHIR Valueset fields are: 

- filter 
- count
- _format 
- url

Is possible to support the  **offset** parameter specified by [FHIR Valueset Operation Expand page](https://www.hl7.org/fhir/valueset-operation-expand.html)

At the moment accessing a large table isn't possible, even with pagination.

One example: https://clinicaltables.nlm.nih.gov/fhir/R4/ValueSet/icd10cm/$expand?_format=json&count=10

where total record count is 72748 and max count parameter of API is 500.

Thank you in advance

**Comment by plynchnlm** [comment] 2021-12-03 14:26
The reason we didn't bother with an offset parameter is that this API service was designed with form-field autocompletion in mind.  In such a context, users would not want usually want to see more than a few items, though we allow up to 500.  Could you share what your use case is for wanting an expansion that exceeds 500 items?  If you are looking to download all of ICD-10-CM, you could just get it from the CDC:  https://www.cdc.gov/nchs/icd/icd10cm.htm.

**Comment by scicco** [comment] 2021-12-09 10:42
I understand your point. I've actually already downloaded and imported all entries from CDC, but parsing the xml file of table version is not straightforward as querying your service (with the FHIR endpoint) and increment offset to import all. 

Anyway thank you for your clarification.

**Comment by plynchnlm** [comment] 2021-12-10 15:29
If I remember correctly I think we use the plain text version, because it is much easier to parse.  See https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Publications/ICD10CM/2022/ and the Code Descriptions zip.zip file.  I am going to close this, as I think you will find the text file easy to work with.

**Closed as completed by plynchnlm** 2021-12-10 15:29 UTC

**Comment by plynchnlm** [comment] 2024-01-24 21:36
FYI, though it is probably too late for your needs, we now provide an offset parameter, though total count + offset is limited to 7,500.

**Comment by scicco** [comment] 2024-02-21 12:30
> FYI, though it is probably too late for your needs, we now provide an offset parameter, though total count + offset is limited to 7,500.

Thank you for the update. Unfortunately, the fixed limit of 7,500 doesn't allow to read all values page by page in a loop, so it doesn't apply my use case 🥲

**Comment by plynchnlm** [comment] 2024-02-22 17:27
You could still get the values a piece a time by using the terms parameter to get all the codes starting with A, then all the codes starting with B, etc.  That seems to work until you get into the 30,000+ S codes, for which you would need to do search for "S0", "S1", etc.
For example:
https://clinicaltables.nlm.nih.gov/api/icd10cm/v3/search?sf=code&df=code,name&terms=A&maxList=7500
